---
- hosts: all
  become: true
  tasks:
    - name: Create Docker network
      docker_network:
        name: iot_network
        state: present

    - name: Run RabbitMQ
      docker_container:
        name: rabbitmq
        image: arturnulp/iot-rabbitmq:latest
        networks:
          - name: iot_network
        ports:
          - "1883:1883"
          - "5672:5672"
          - "15672:15672"
        env:
          RABBITMQ_DEFAULT_USER: "myuser"
          RABBITMQ_DEFAULT_PASS: "mypassword"  

    - name: Run Data Generator
      docker_container:
        name: data-generator
        image: arturnulp/iot-data-generator:latest
        networks:
          - name: iot_network
        env:
          TENANT: "001"
          SENSOR_TOKEN: "123"
          BROKER_HOST: "rabbitmq"
          BROKER_PORT: "1883"
          BROKER_USER: "myuser"
          BROKER_PASSWORD: "mypassword"
          RUN_MODE: "STREAM"
          NUMBER_OF_ITERATIONS: "1"
          WATER_QUALITY_TOPIC: "building/floor_1/bedroom/water_quality"
          WEATHER_TOPIC: "building/weather"
          AIR_QUALITY_TOPIC: "building/001/air_quality"

    # - name: Run Elasticsearch
    #   docker_container:
    #     name: elasticsearch
    #     image: elasticsearch:8.5.1
    #     networks:
    #       - name: iot_network
    #     ports:
    #       - "9200:9200"
    #     env:
    #       discovery.type: "single-node"
    #       xpack.security.enabled: "false"
    #       ES_JAVA_OPTS: "-Xms1g -Xmx1g"  

    # - name: Run Mongo DB
    #   docker_container:
    #     name: mongodb
    #     image: mongo:5
    #     networks:
    #       - name: iot_network
    #     ports:
    #       - "27017:27017"
    #     env:
    #       MONGO_INITDB_ROOT_USERNAME: "admin"
    #       MONGO_INITDB_ROOT_PASSWORD: "secret"

    # - name: Run Mail Server
    #   docker_container:
    #     name: mail
    #     image: mailhog/mailhog
    #     networks:
    #       - name: iot_network
    #     ports:
    #       - "8025:8025"

    # - name: Run Data Processor
    #   docker_container:
    #     name: data-processor
    #     image: arturnulp/iot-data-processor:latest
    #     networks:
    #       - name: iot_network
    #     ports:
    #       - "8080:8080"
    #     env:
    #       ELASTICSEARCH_HOSTNAME: "elasticsearch"
    #       ELASTICSEARCH_PORT: "9200"
    #       SPRING_RABBITMQ_HOST: "rabbitmq"
    #       SPRING_RABBITMQ_PORT: "5672"
    #       SPRING_RABBITMQ_USERNAME: "myuser"
    #       SPRING_RABBITMQ_PASSWORD: "mypassword"
    #       SPRING_DATA_MONGODB_HOST: "mongodb"
    #       SPRING_DATA_MONGODB_PORT: "27017"
    #       SPRING_DATA_MONGODB_DATABASE: "iot"
    #       SPRING_DATA_MONGODB_USERNAME: "admin"
    #       SPRING_DATA_MONGODB_PASSWORD: "secret"

    # - name: Run Kibana
    #   docker_container:
    #     name: kibana
    #     image: kibana:8.5.1
    #     networks:
    #       - name: iot_network
    #     ports:
    #       - "5601:5601"                   